### ISSUE TITLE
"NON" binary file writing error at DDES developing version.

### ISSUE THREAD

**Issue by yukaiweng** [su2code/SU2#477] opened 2017-11-26 19:17 UTC
Dear Team SU2:

Apologize for the re-post this issue since I accidentally closed the last one.

I've downloaded and compiled the latest developing version of SU2 with DDES feature.
However, since I need to read the solution file in the non-binary format for further process. I both set NO at WRT_BINARY_RESTART and READ_BINARY_RESTART option.
However, when I open the non-binary restart file, say by excel, some solution values are merged into the wrong column or just missing. And now these mislocated data make the non-binary solution file cannot be used for restart simulation ( a Diverged warning message will pop up ).
Also based on the observation, these kinds of data writing error appeared in every 9 or 10 point id in general, for example, the first error shows in pointID # 9, then # 18...so on. The example error file is attached.

Could you please advise me if there is any quick fix for this issue. Or is there any converter inside the SU2 that I can run the simulation in binary first then convert them later?

I put some sample original non-binary file which has mislocated or missing data, and cannot be read as restart file in google drive [here](https://drive.google.com/drive/u/1/folders/1kmAqTV-HyHH6y2o1zxPVLEJ5pU2LRebl) and another bad written non-binary file is attached.
[badfile.zip](https://github.com/su2code/SU2/files/1504155/badfile.zip)

Sincerely,
Yu-Kai Weng

**Comment by economon** [comment] 2017-11-27 02:59
@yukaiweng: no problem on the repost. A couple comments...

1. I am not able to reproduce the problem on my mac, but I have a suspicion that the line endings in the text files could be causing an issue. Are you working on Windows? There may be a problem with the line endings that can resolved by using the "dos2unix" or "unix2dos" utility on linux that can format the file in the correct direction. Check this out any time you move files between Linux/Mac <-> Windows.

2. You can always convert between the two file types using the config options and restarting for one iteration, e.g. if you have a binary restart file and you restart with

WRT_BINARY_RESTART= NO
READ_BINARY_RESTART= YES
EXT_ITER= 1

you will get an ASCII restart upon completion. You can do also do this in the other direction to get a binary restart from ASCII.

Hope this helps,
Tom

**Comment by yukaiweng** [comment] 2017-11-27 16:48
@economon Hello Dr. Economon, thank you very much for the replying.

1. I tried using unix2dos to convert the file attached to the previous post, but the problem remains as picture shown (attached and highlighted) and these non-binary files cannot be read in SU2 when running restart simulation. Is it possible I did not configure it correctly during the installation? 
My configure command is: "./configure --prefix=user-dir --enable-mpi --with-cc=mpicc --with-cxx=mpicxx"

2. Thanks for the suggestion. And since I am using MATLAB to post-process the data and trying to import the binary restart data directly into MATLAB, could you please advise me the precision and other information of the binary restart file?


Again thank you very much for your helping with this issue.
Sincerely
![picture1](https://user-images.githubusercontent.com/33880907/33277349-40eaa6d8-d366-11e7-970f-1ae712fb449b.jpg)
![picture2](https://user-images.githubusercontent.com/33880907/33277354-4374751e-d366-11e7-8f8e-4b6a81c5b78f.jpg)

**Comment by economon** [comment] 2018-01-24 08:02
Unfortunately, I have not been able to recreate this issue on my systems with the simple test case that you shared @yukaiweng. 

@talbring or @EduardoMolina, if you have some time, could you give the attached toy problem a try on your machines? I ran for a couple of unsteady iterations and then restarted on the third iteration (successfully for me). I think we're just missing something simple...

[ascii_restart_test.zip](https://github.com/su2code/SU2/files/1659029/ascii_restart_test.zip)

**Comment by economon** [comment] 2018-01-29 19:06
We have resolved this issue: the problem was with the particular combination of MPI implementation and compiler. The problem appeared with Intel MPI (mpigcc for the Intel(R) MPI Library 2017 Update 2 for Linux*) and GCC 6.3.0. Switching to an OpenMPI implementation fixed the issue. As this may be a machine-specific problem, we will close the issue, but please be advised of possible problems with this combination.

**Closed by economon** 2018-01-29 19:06 UTC

**Comment by msahinae00** [comment] 2020-05-27 03:53
Hi

I am using SU2-6.2.0 with PYAMG library to solve RANS equations. l have similar ascii write problem. For initial runs with SU2, i used binary format. Unfortunately, now PYAMG requires only ascii output and l have to sort it out. I compiled with SU2 with openmpi/1.8.8-gcc-4.8.5 using

./configure --prefix=/truba/home/mesahin/LIB_ALL/SU2-6.2.0+PYAMG  -enable-mpi -enable-metis --with-cxx=mpicxx  --enable-PY_WRAPPER  CXXFLOGS='O3'

Thanks
