### ISSUE TITLE
Restart interpolation hangs

### ISSUE THREAD

**Issue by rois1995** [su2code/SU2#2396] opened 2024-12-18 22:48 UTC
I was finally able to obtain this problem on "reasonable" mesh sizes. To me, it seems that some ranks are remain stuck in the while loop at line SU2_CFD/src/solvers/CSolver.cpp:3260 even though the master rank says that the interpolation has finished. I was able to reproduce this error with 8-12-16-18 cores but no error was encountered with 4-6-10-14-20 cores. It does not change if a combination of threads and cores is used as long as the number of cores is among the list of those reproducing the error.

Digging a little bit in the code, it seems to be stuck in the while loop as said before. In particular, it seems that for some points it is not able to pass the two checks at lines 3275 and 3276 of the same file. I will try digging more.

At the following link you can find the files to reproduce the error.

https://polimi365-my.sharepoint.com/:f:/g/personal/10507725_polimi_it/EjMatPcoa8hPsvVyADfOZL0BQ7YMu7K3WvZaSCaoEeXy1Q?e=x3nRZy

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - C++ compiler and version: gcc 10.2.0
 - MPI implementation and version: mpirun (Open MPI) 4.1.6
 - SU2 Version: v8.0.1

**Comment by pcarruscag** [comment] 2024-12-19 00:08
4 years since I wrote that according to GitHub...
It's possible that since we only look at domain points (non halos) for the interpolation some parts of the graph become disconnected and the information doesn't make it there.
You can try replacing some of the loops on nPointDomain by nPoint so that we also information to come from halo points too.

**Comment by rois1995** [comment] 2024-12-19 12:01
The problem is that no point on the boundary of the new mesh was selected to be the nearest neighbor of a point in the old mesh. Thus, since the second step allows only points that are on the boundary to be selected as donor points for other boundary points, it does not find any that has been mapped and then it cannot escape the while loop. Still, I don't understand how a core can be trapped inside the while loop and the master still prints that interpolation has finished.

**Comment by pcarruscag** [comment] 2024-12-21 18:14
Removing the "boundary == boundary" restriction after 8 recursions let's the interpolation finish in about 20 recursions on 6 and 8 cores.
However the result looks bad with a large area with values greater than 1e20. Are you initializing from a diverged solution?
Can you upload the mesh associated with the restart file?

**Comment by pcarruscag** [comment] 2024-12-21 18:15
Initializing the halo points didn't make a difference.

**Comment by rois1995** [comment] 2024-12-21 18:17
Yes, I am restarting from a diverged solution, that's why it looks bad. Tomorrow I will try and upload the converged one.

**Comment by pcarruscag** [comment] 2024-12-26 00:00
There are some rows of nodes along the bottom that don't get data, that's what is making the interpolation take longer and stall if we boundary points from receiving from the interior.

**Comment by rois1995** [comment] 2024-12-26 15:05
I was referring to the first ste of the interpolation, when the values from the older mesh are copied to the nearest points of the new one. I guess it should just slightly improve the initial convergence of the solver as at least the points on the boundary better satisfy the boundary conditions.

**Comment by pcarruscag** [comment] 2024-12-28 18:50
Probably but then you need the original mesh and config and the whole thing becomes a lot more complex.
It doesn't hang anymore so I'll close this issue, thanks for finding a case to reproduce the problem.

**Closed by pcarruscag** 2024-12-28 18:50 UTC
Labels: bug
