### ISSUE TITLE
Issues with the Updated IO 4c4c296

### ISSUE THREAD

**Issue by cspode** [su2code/SU2#283] opened 2016-06-05 18:33 UTC
Hi,

After the "Update IO" on April 17 (4c4c296) commit,  the Yplus seems to be not right in the output files. The skin friction has been split in x,y and z components and after that I noticed that the y+ in the outputs started to be strange. It's may be a MPI synchronization issue. And just another quick question: Is there any motivation to change the names from "Pressure_Coefficient" to "C<sub>p</sub>" in the output?

Best,

Cleber.

**Comment by abdulhaq-e** [comment] 2016-06-11 19:28
Regarding the name change, I would like to add that Paraview doesn't show the variable name correctly when using those subscripts.

**Comment by economon** [comment] 2016-06-12 07:05
Thanks for both comments. We're looking into the y+ issue you mention, and I'll note anything that I find here.

The name changes are just for aesthetics (and convention). However, since they do not work for ParaView, we can revert them in that case.

**Comment by hlkline** [comment] 2016-06-14 18:14
I suggest that we add a test to the regressions that will check the file output format - we already have a routine to diff two files in the python scripts, so this should be fairly straightforward. 
My thought here is that this would include very small cases, with just one iteration and/or just running SU2_SOL, to check that the header format hasn't changed in all the output formats.

This is something we don't usually check for, especially in paraview output since most of us don't use that. It'll add some overhead for developers when the output content or format is changed (we'll need to update the reference file in the test cases repo), but since this is something likely to cause inconvenience to users (all of a sudden everyone needs to update their tecplot layout, etc), that's not such a bad thing.

**Comment by economon** [comment] 2016-06-14 20:53
I can report that we did find a couple of small issues with the y+, depending on the file format. Those have been fixed in a recent pull request, so now the current develop branch contains the updates. For ParaView, the variable labels have been reverted to the originals.

Thank you again for opening this issue: it led directly to improvements in the code!

**Closed by economon** 2016-06-14 20:53 UTC
