### ISSUE TITLE
A bug in variable_direct_mean.cpp

### ISSUE THREAD

**Issue by paulhzhang** [su2code/SU2#307] opened 2016-09-18 07:51 UTC
In SU2_CFD\src\variable_direct_mean.cpp 
….
 if (Gradient_Primitive != NULL) {
    for (iVar = 0; iVar < nPrimVarGrad; iVar++)
      if (Gradient_Primitive!=NULL) delete [] Gradient_Primitive[iVar]; // Should be if (Gradient_Primitive[iVar]!=NULL) 
    delete [] Gradient_Primitive;
  }
  if (Gradient_Secondary != NULL) {
    for (iVar = 0; iVar < nSecondaryVarGrad; iVar++)
      if (Gradient_Secondary!=NULL) delete [] Gradient_Secondary[iVar];//should be if (Gradient_Secondary[iVar]!=NULL) 
    delete [] Gradient_Secondary;
  }
….

**Comment by hlkline** [comment] 2016-09-19 04:17
Thanks for bringing this to our attention. Would you like to submit a pull request with this change? 
It is a little more work on your part [see the developer section of the SU2 github wiki for further instructions], but this way your contribution can be merged in after passing some regression tests, and since this is only a couple of lines to change it is a good way to get used to the pull request system if you haven't used that before.

**Comment by paulhzhang** [comment] 2016-09-22 02:40
Thanks for suggestion. Good practice to do!
Paul

**Comment by talbring** [comment] 2016-09-22 12:50
Thanks again for opening the pull request to solve this bug!

**Closed by talbring** 2016-09-22 12:50 UTC
