### ISSUE TITLE
Memory usage leading to partial use of resources 

### ISSUE THREAD

**Issue by aeroamit** [su2code/SU2#291] opened 2016-07-09 08:40 UTC
I am trying to run a big case with approximately 60 million mesh size. I am running it on multiple nodes, each having 8 processors. Problem is that I am able to make use of only 4 cores out of 8 available on each node for this size of problem and rest cores will be idle. 
If I try to run it on more cores, it fails during start and throws a message something like -- error while converting array I4 -I5 for CGNS ..........
But while checking the memory usage during solution time with 4 core per node usage (24 GB memory for each node and around 60 such nodes), it shows only 30-35% memory usage for each node.
May be something need to be improve during start up phase while reading CGNS and converting to SU2 data structure, parmetis phase etc.
This will enable efficient usage of resources for this size problem 

For smaller size problems, I am able to use all the cores on each node.

**Comment by economon** [comment] 2016-07-09 20:43
Hmm.. I'm a bit surprised by this, since in the latest versions of the code, the memory required during partitioning does not exceed the memory required during the solve.

Are you using the latest version of SU2? We've been working on even more memory optimization lately in the fix_periodic branch, if you'd like to give that a try.

I am more concerned with the error you are receiving from the CGNS reader though, and think something funny might be happening there. Can you please share more info on the error?

**Comment by aeroamit** [comment] 2016-07-11 14:22
I will get back after some more experiments. Waiting to get some resources to run the tests.

**Comment by aeroamit** [comment] 2016-07-12 11:37
I did few tests following are the details -
**While trying to use all 8 cores per node-**

Loading section Connect_PRISM of element type Prism.
malloc failed for element data
malloc failed for element data
............

malloc failed for element data
Error allocating I4->I8 data array...
malloc failed for element data
Error allocating I4->I8 data array...
malloc failed for element data
................
malloc failed for element data
malloc failed for element data
Loading section Connect_TETRA of element type Tetrahedron.


**While trying 6 cores in each node**

Loading section Connect_PRISM of element type Prism.
malloc failed for element data
malloc failed for element data
malloc failed for element data
malloc failed for element data
malloc failed for element data

**Finally settled with 4 cores at each node memory usage while running them on 4 nodes are -** 

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                                                         
 4652 aero      30  10  872m 746m  10m R  100  3.1  43:03.38 SU2_CFD                                                                                                                                         
 4653 aero      30  10 1076m 951m  10m R  100  3.9  43:12.10 SU2_CFD                                                                                                                                         
 4654 aero      30  10 1162m 1.0g  10m R  100  4.3  43:15.15 SU2_CFD                                                                                                                                         
 4655 aero      30  10 1458m 1.3g  10m R  100  5.5  43:08.96 SU2_CFD      

**With above, memory usage seems to be around 16.8 % of 24 GB RAM**

Hope I am not missing something else (some other usage etc...) and what should be the approximate memory requirement for such mesh sizes (around 60 million or may be general guideline of memory with mesh size) ?

Regards
Amit

**Comment by aeroamit** [comment] 2016-07-13 13:20
I also tried fixed-periodic branch, it does not help with this issue

**Comment by economon** [comment] 2016-07-13 18:09
Amit,

I see, thank you for the info. Those malloc errors are coming from within the CGNS library, so it's a bit tough for us to treat directly. A few more questions...

1. Which version of CGNS are you using?

2. Can you please check if there are any hard limits on heap allocation / memory usage for your account on this particular HPC resource (I have seen this before on some systems)?

3. To help isolate the issue, can you please convert the CGNS mesh to our SU2 ASCII format and try again? It will be slower, of course, but it will help identify whether the issue is purely memory usage.

Tom

**Comment by aeroamit** [comment] 2016-07-14 15:50
1- I am using CGNS 3.2.1, which is quite recent.

2- There is no restriction on memory usage, I just checked/confirmed it. 

3- I tried another case a while earlier by converting CGNS to SU2 and than using it for run but that too failed with higher number of cores per node (similar situation). I will give another try with this method and report.

Regards

**Comment by aeroamit** [comment] 2016-07-18 17:24
For trial, I ran a copy of same problem on remaining four cores and it goes through. So I am able to run 2 same size problem on all the available cores (4 each) but not able to run same job with all the 8 cores.

There may be small bug. Is memory usage peaking at some instance during startup, due to which it is not able to run on all cores? May be.

Thanks and Regards 
Amit

**Comment by economon** [comment] 2019-01-31 06:22
@aeroamit : as you know, we have since updated the CGNS version and ship/build it automatically with SU2. Are you still having any issues, or can we close this for now?

**Comment by aeroamit** [comment] 2019-01-31 16:59
Hi @economon : I posted this around 2 and half years back. This doesn't seem to be an issue now (1- Due to continuous development and 2-  hardware upgrades). I will close this for now. 

Thanks

**Closed** 2019-01-31 16:59 UTC
