### ISSUE TITLE
Su2 V5.0.0 developer branch sliding interface feature: problem with post processed Tecplot output file -reg

### ISSUE THREAD

**Issue by jkputtam** [su2code/SU2#417] opened 2017-07-24 07:03 UTC
Dear Team SU2,

I would like to inform you that, while post processing the results of a 3-zone sliding interface 3D simulation with Tecplot, it is noticed that output file of one of the zone (The outermost zone, within which remaining two zones are present) is showing 80% of data as ~x.xxxe-317 and 10% as nan. Whereas the run went very very smoothly with very good fall in residue in all the blocks without any non-physical points. Hence I am suspecting that there is some problem in post processing (SU2_SOL) it self. Please let me know how to solve this issue.

Regards,
Jyothi Kumar Puttam.

**Comment by LaSerpe** [comment] 2017-07-24 07:52
Dear Jyothi,

Just a couple of questions before start looking into this: can you please check/confirm that the restart files (the ones that are post-processed by the SU2_SOL) do not show any of such issues?
I am assuming you are running your simulation in parallel, can you also check if those wrong values are written in the tecplot output also if you run your computation serially (so that SU2_SOL is not needed)?
Last one, what about the paraview output? Is that one ok?

It would be great if you could provide the config file and the grid, so that I can reproduce the very same behaviour.

Cheers,
Giuilo

**Comment by jkputtam** [comment] 2017-07-24 08:53
Dear Giuilo,

Thank you so much for your quick response.

Here are answers for your questions:
1. Restart files are in Binary format.
2. I am running this simulation in parallel mode on 160 cores.
3. Paraview output file(.vtk) is also having all the issues, what I faced with Tecplot file.

I am very much ready to provide you the config & grid files, but grid file is approx. 394MB. Shall I send through drop box?

Thanks & Regards,
Jyothi Kumar Puttam.

**Comment by jkputtam** [comment] 2017-07-24 13:25
Dear Giuilo,

I would like to give some more information regarding your first question. Actually I wrote the restart files in ASCII format. Those are absolutely OK after zero time step, but where as Tecplot file of outer zone has all errors, which I discussed.

Thanks & Regards,
Jyothi Kumar Puttam.

**Comment by LaSerpe** [comment] 2017-07-25 07:49
Dear Jyothi,

that is a quite large grid actually, probably dropbox is the best solution.
Just give me the address and I'll send you a link.

regards,
Giulio

**Comment by jkputtam** [comment] 2017-07-25 10:39
Dear Giuilo,
I would like to request you to download the grid & cfg files from dropbox at the following link.
https://www.dropbox.com/sh/10i08tl6pqx8usm/AABvUfOo1TI1Z0vraYXMFBfja?dl=0
Please let me if you face any problem in downloading.

Thanks & Regards,
Jyothi Kumar Puttam.

**Comment by LaSerpe** [comment] 2017-07-25 15:44
Dear Jyothi,
thanks, I managed to download all files correctly.
I noticed that in your config file you are using the MARKER_FSI_INTERFACE option, which is actually outdated (currently it should read MARKER_ZONE_INTERFACE), so I am assuming that you are not running the latest version of the develop branch.
First, I would suggest you to update SU2 on your local server, as the issue might have been solved in one of the latest updates.
Indeed, I was able to run the test case and the output files look good using the latest version.

By the way, I had troubles using the SA turbulence model (a segmentation fault which I have to investigate further, but the case run just fine using the SST model)

Let me know if you still get the "nan" issue in the output files using the latest version of the develop branch.

cheers,
Giulio

**Comment by jkputtam** [comment] 2017-07-26 13:00
Dear Giuilo,

I would like to thank for your patience in downloading and running the case. I have downloaded & installed the develop branch code afresh and tried to run the case with SST turbulence model, but unfortunately I got an error sating, "AOA: option appears twice", while reading the config file it self. I think it is due to little mistake with any of newly updated files. Please look into this matter once. 

I am sorry for troubling you many times.

Thanks & Regards,
Jyothi Kumar Puttam.

**Comment by vdweide** [comment] 2017-07-26 13:06
Dear Jyothi,

This error message indicates that you have specified the AOA option (angle of attack) option twice in your cfg file. Check if this is indeed the case and remove one.

Regards,

Edwin

**Comment by jkputtam** [comment] 2017-07-26 13:43
Dear Edwin,

Thanks for your quick response. I thoroughly verified my config file, AoA option was given only once. I am not getting any clue about this error. In-fact, I made only two modifications to the config file, which I have sent to Dr. Giuilo, yesterday. Those two are: 1. MARKER_ZONE_INTERFACE option from MARKER_FSI_INTERFACE 2. SST Turbulence model from SA. Then I arrived at new config file for the today downloaded code from develop branch. Hence I suspected minor mistake in any one of newly updated files to develop branch.

Thanks & Regards,
Jyothi Kumar Puttam.

**Comment by talbring** [comment] 2017-07-26 13:56
Hi Jyothi,

I tried your config file and I cannot reproduce this issue here.

**Comment by jkputtam** [comment] 2017-07-26 14:26
Dear Tim,

Thanks for your response. I would like to inform you that I have downloaded the develop branch code nearly 9hrs ago from git and installed. May I know, are using the fresh code available from develop branch.

Regards,
Jyothi Kumar Puttam.

**Comment by salvovitale** [comment] 2017-07-26 19:32
Dear Jyothi,
regarding the error with the option AOA  given twice. the problem is related to the fact that in your config file you are giving the option with the "o" lower case. If you update the option from 
"AoA" --> "AOA" it will work.

regards

Salvo

**Comment by jkputtam** [comment] 2017-07-27 06:57
Dear Salvo,

Thanks a lot. I appreciate your observation in tracing out the cause of "lower case o" used in my config file. My AoA problem is solved. Just I replaced AoA with AOA, then the run took-off. But in earlier versions AoA option was working and never used AOA upto now. This is the first time I am using AOA in my config file. Anyway thanks once again.

Regrads,
Jyothi Kumar Puttam.

**Comment by talbring** [comment] 2017-07-27 07:25
I'm glad that it is working for you know. But this behavior is definitely not correct. In fact, for me it also works with AoA without giving a problem (which is the intended behavior since every left-hand side string is transformed to upper-case).

**Comment by jkputtam** [comment] 2017-07-27 12:50
Dear Giuilo,

I am able to simulate the case with fresh download from develop branch and got post processed data for Tecplot without any error. Thanks a lot for your assistance in this regard. But surprisingly I also faced problem with SA turbulence model, whereas SST is going smooth. SA turbulence model is working fine with develop branch code, which was downloaded may be 2 months ago.

Thank you so much Giulio once again!

Regards,
Jyothi Kumar Puttam.

**Comment by LaSerpe** [comment] 2017-07-27 13:17
Hi Jyothi, 

yes, I am indeed aware that there is something to fix with the SA turbulence model and I am already working to solve it, so that I can push a fix as soon as possible.

Regarding the MACH_MOTION option, that is a non-dimensional value you can set to initialize a viscous flow and for computing force coefficients when using dynamic meshes.
Within the SU2 folder you can find the config_template.cfg file that lists all of the options available in SU2. 
There, all options are briefly described and an example of their usage is also provided.

By the way, I am happy that you are now able to run your simulation correctly (using the SST model), and thanks to all the SU2 developers that also contributed to help you having your computations running.

I am closing this issue, feel free to re-open it if there is something more you (or someone else) want to discuss.
Giulio

**Closed by LaSerpe** 2017-07-27 13:17 UTC
