### ISSUE TITLE
compute_polar.py error when optimization objective is not defined

### ISSUE THREAD

**Issue by alexfeld** [su2code/SU2#545] opened 2018-06-27 18:01 UTC
If `OPT_OBJECTIVE` is not defined in the `.cfg` file `compute_polar.py` creates a dummy. However, the dummy lacks a surface marker so it fails on the post processing step. Updating the dummy logic to the following seems to work (line 379 in the current version) .

```(python)
if 'OPT_OBJECTIVE' not in konfig:
                obj = {}
                obj['DRAG'] = {'SCALE':1.e-2, 'OBJTYPE':'DEFAULT', 'MARKER': 'None'}
                konfig.OPT_OBJECTIVE = obj
```

**Comment by erangit** [comment] 2018-06-28 01:11
alexfeld
Thanks for your support in the compute_polar.
However, I don't manage to reproduce the failure that you have described. I have run a case
where the cfg file containes no MARKER_DESIGNING definition. Consequently, both 
config_CFD.cfg and config_SOL.cfg had no definition of that marker but nothing failed.
Could you share with me you cfg file so that I will be able to reproduce the error that you
have encountered?
BTW, I havn' t updated yet to 6.1.0 (I'm in 6.0.1). May this be the reason for the different behavior?
Best,
Eran

**Comment by alexfeld** [comment] 2018-07-03 19:38
My apologies for the long delay. I did notice this bug after updating to the latest version.

Using the following files and the `euler/oneram6/mesh_ONERAM6_inv_ffd.su2` mesh from the test cases: 

[run_polar_template.sh.txt](https://github.com/su2code/SU2/files/2160777/run_polar_template.sh.txt)
[polarCtrl.in.txt](https://github.com/su2code/SU2/files/2160761/polarCtrl.in.txt)
[base_cfg.cfg.txt](https://github.com/su2code/SU2/files/2160762/base_cfg.cfg.txt)

With the current version of `compute_polar.py`, if lines 285 on are comment in `base_cfg.cfg` then the script will fail. Adding the fix I describe above solves the issue.

Further issues: the moment outputs in lines 458 and 459 are inconsistent with the headers defined in line 332. The ordering of the `z` and `y` moment are reversed. Also, the `x` moment is currently assigned to the `z` moment in the result structure in line 443.

**Comment by WallyMaier** [comment] 2019-06-26 22:14
Resolved in PR

**Closed by WallyMaier** 2019-06-26 22:14 UTC
