### ISSUE TITLE
Incorrect aero coeffs for compressible moving grid simulations

### ISSUE THREAD

**Issue by Daamanbarara** [su2code/SU2#1175] opened 2021-01-22 17:12 UTC
Hello SU2 Community! 

I am simulating flow over a 6-blade propeller and modeling 1/6th of the domain with an assumption that it is axisymmetric. I meshed the computational domain generating an unstructured grid using ANSYS Meshing with a targetted y+<1 and simulated the case using a pressure-based (SIMPLE) solver with S-A turbulence model in Fluent. It is a steady-state simulation and used a frozen rotor approach. Fluent converged after the reduction of continuity residuals by four orders of magnitude.

For simulating the domain in SU2, I had converted the mesh into CGNS format, simulated with similar settings using SU2's RANS Solver (S-A) with rotating domain and periodic boundary conditions. The simulation converges as the residuals drop by two orders of magnitude and monitors stabilize after 30k iterations. 

On checking the contours, the SU2 predicts relatively high y+ values, especially near the junction of propeller blade root and spinner, where the values go up to y+~250, while it is around y+=1-2 in the rest of the domain. Whereas, Fluent predicts the y+<1 throughout for the same mesh. The values of forces and moment are off by two orders, on comparing it with the Fluent and experimental results. But, flow-field and contours of pressure distribution look similar for both SU2 and Fluent. I'm wondering what might have led to the difference in the results. I have refined the mesh, but it only reduces y+ by a small number. I have attached the config file and would like some inputs. Thanks in advance.

[Prop_config.txt](https://github.com/su2code/SU2/files/5857368/Prop_config.txt)

**Comment by pcarruscag** [comment] 2021-01-22 18:03
In your CFL online post you forgot to mention that for the most part the y+ 1-2..........

Fluent is a cell centered code, whereas SU2 is vertex centered, I'm guessing this explains the double y+ problem (not 450 times...)

I'm guessing the high values are caused by over estimated gradients near corners, you can try using NUM_METHOD_GRAD= WEIGHTED_LEAST_SQUARES which might cope better with sharp geometric features.

The thrust and torque output from SU2 are non dimensional equivalent to -CFz and -CMz respectively. How are you comparing them to Fluent?

you should always use LINEAR_SOLVER_PREC= ILU with JST on rans grids, it will probably let you use higher CFL.

**Comment by Daamanbarara** [comment] 2021-01-23 10:48
Thank you for replying!

Yeah, apologies as I forgot to add that part in my CFD online post. I agree with the fact that there would be a certain difference in the values between the two solvers. But as not as large as what I am getting, as you said. After my initial post on CFD online, I meshed with finer settings and ran different meshes only to find the drop in y+ near that sharp region of the blade root-spinner junction. It went from 450 to 200 (latest).

I will run the simulation with NUM_METHOD_GRAD= WEIGHTED_LEAST_SQUARES as mentioned by you, as I had been running it with GREEN_GAUSS up until now because it turns out to be faster.

In Fluent, the thrust and torque values are in dimensional form and it reports the forces on propeller and spinner in the x-direction as my flow is in that direction.

**Comment by Daamanbarara** [comment] 2021-01-23 11:05
Thank you for replying!

Yeah, apologies as I forgot to add that part in my CFD online post. I agree with the fact that there would be a certain difference in the values between the two solvers. But as not as large as what I am getting, as you said. After my initial post on CFD online, I meshed with finer settings and ran different meshes only to find the drop in y+ near that sharp region of the blade root-spinner junction. It went from 450 to 200 (latest). This could affect the solution significantly.

I will run the simulation with NUM_METHOD_GRAD= WEIGHTED_LEAST_SQUARES as mentioned by you, as I had been running it with GREEN_GAUSS up until now because it turns out to be faster. 

In Fluent, the thrust and torque values are in dimensional form and it reports the forces on propeller and spinner in the x-direction as my flow is in that direction. I am not sure why -CFz and -CMz? I know that the factor to get the dimensional force is calculated using surface normals are in the z-direction and the reference area is based on that.

I'll run the simulation with the settings as suggested by you and update it.

**Comment by pcarruscag** [comment] 2021-01-23 11:13
> I am not sure why -CFz and -CMz for SU2?

I guess the person who implemented those outputs felt quite strongly about the z axis.

> x-direction as my flow is in that direction

You need to look at CFx and CMx from SU2 then. Use WRT_FORCES_BREAKDOWN = YES, I think the breakdown file has dimensional forces, or at least the reference density, velocity, pressure, etc.

**Comment by Daamanbarara** [comment] 2021-01-23 11:17
Yes, I have activated the option for the force breakdown in my configuration file and currently running it. I'll update you with the findings I get.

**Comment by pcarruscag** [comment] 2021-01-23 11:22
> near that sharp region of the blade root-spinner junction. It went from 450 to 200 (latest). This could affect the solution significantly.

It would only affect viscous contributions to forces / moments which should be minimal.
Can you post a picture of what the solution (e.g. skin friction coefficient) and mesh look like in those areas? Some kind of slice that shows what the boundary layer region looks like would be ideal.

**Comment by Daamanbarara** [comment] 2021-01-24 10:53
I have attached the contours of skin friction coefficient and y+ of the region. I have also attached, the snip of surface mesh as well as the volumetric mesh, zooming in that region. 

![y+](https://user-images.githubusercontent.com/61012294/105628035-b3a54900-5e3a-11eb-8111-3b67136b8813.JPG)
![Cf](https://user-images.githubusercontent.com/61012294/105628036-b3a54900-5e3a-11eb-8184-8eb317faecfd.JPG)
![Vol_Mesh](https://user-images.githubusercontent.com/61012294/105628032-b2741c00-5e3a-11eb-8882-ed0c9a746a0e.JPG)
![Mesh](https://user-images.githubusercontent.com/61012294/105628033-b30cb280-5e3a-11eb-94d5-0b11f5ed99cc.JPG)

**Comment by Daamanbarara** [comment] 2021-01-26 14:02
Hi, thank you for the suggestions. I simulated with the suggested settings, and the values of y+ in the spinner-blade junction region have reduced to 140. I am specifically interested in knowing thrust and moment, and those turned out to be similar to the previous runs, which are two orders of magnitude lower than experimental ones. 

> You need to look at CFx and CMx from SU2 then. Use WRT_FORCES_BREAKDOWN = YES, I think the breakdown file has dimensional forces, or at least the reference density, velocity, pressure, etc

The force breakdown file generates non-dimensional coefficients using the reference area on the z-plane. If I want to find the dimensional forces in the x-direction (flow direction), should the non-dimensional factor be based on the reference area on the z-plane or the x-plane?

**Comment by pcarruscag** [comment] 2021-01-26 14:09
Upload the breakdown file please.

**Comment by Daamanbarara** [comment] 2021-01-26 14:11
[forces_breakdown.txt](https://github.com/su2code/SU2/files/5873768/forces_breakdown.txt)

**Comment by pcarruscag** [comment] 2021-01-26 14:53
Thrust should be -11.12N and torque 0.8329Nm, not accounting for number of blades. Is that closer to what you expect?

The coefficients are computed with a reference velocity based on Mach motion, but the dimensional factor shown in the breakdown file considers the free stream velocity instead... (silly and avoidable bug).

**Comment by Daamanbarara** [comment] 2021-01-26 15:05
Yes, that is closer to the expected values. 

Ah right! That makes a lot of sense now. Thank you for helping me out with this.

**Comment by pcarruscag** [comment] 2021-01-26 15:14
No prob, I'll put a fix for this in the next version.
The dimensional factor is 0.5 * rho_inf * MachMotion^2 * gamma * R * Tinf * RefArea, and * RefLen for the Moment.

For the y+ on those corner areas I cannot do much.

**Comment by Daamanbarara** [comment] 2021-01-26 16:59
Thanks. 

No worries, I believe it is probably a problem-specific issue, specially concerning ones with sharp geometric features.

**Closed** 2021-01-30 14:26 UTC
Labels: bug

**Comment by joelanders-lim** [comment] 2024-02-15 18:59
> Thrust should be -11.12N and torque 0.8329Nm, not accounting for number of blades. Is that closer to what you expect?
> 
> The coefficients are computed with a reference velocity based on Mach motion, but the dimensional factor shown in the breakdown file considers the free stream velocity instead... (silly and avoidable bug).

How did you get the values of -11.12N and 0.8329Nm from the breakdown file, and output file? I'm not sure where/how to calculate it.

I'm new at SU2. and want to use it for VAWT torque calcs, so stumbled upon this discussion in my searches.

Many thanks
